from enum import Enum


class SkillEnum(str, Enum):

    # Programming Languages
    C = "C"
    Cpp = "Cpp"
    Java = "Java"
    Python = "Python"
    JavaScript = "JavaScript"
    TypeScript = "TypeScript"
    Go = "Go"
    Rust = "Rust"
    Kotlin = "Kotlin"
    Swift = "Swift"
    PHP = "PHP"
    CSharp = "C#"
    R = "R"
    Dart = "Dart"
    Scala = "Scala"
    Bash = "Bash"
    Assembly = "Assembly"
    MATLAB = "MATLAB"
    Groovy = "Groovy"
    Haskell = "Haskell"
    Elixir = "Elixir"
    Julia = "Julia"
    COBOL = "COBOL"
    Fortran = "Fortran"
    Solidity = "Solidity"
    VBA = "VBA"
    Objective_C = "Objective-C"
    PowerShell = "PowerShell"
    Scratch = "Scratch"
    Crystal = "Crystal"
    Nim = "Nim"
    Ada = "Ada"
    GDScript = "GDScript"
    FSharp = "F#"
    Perl = "Perl"
    Shell_Scripting = "Shell Scripting"
    WebAssembly = "WebAssembly"
    PLSQL = "PL/SQL"
    ABAP = "ABAP"
    Hack_HHVM = "Hack (HHVM)"
    Zig = "Zig"
    Verilog = "Verilog"
    VHDL = "VHDL"

    # Frontend
    HTML = "HTML"
    CSS = "CSS"
    React = "React"
    NextJS = "Next.js"
    Angular = "Angular"
    VueJS = "Vue.js"
    Tailwind_CSS = "Tailwind CSS"
    Bootstrap = "Bootstrap"

    # Backend
    NodeJS = "Node.js"
    ExpressJS = "Express.js"
    Django = "Django"
    Flask = "Flask"
    FastAPI = "FastAPI"
    Spring_Boot = "Spring Boot"
    ASP_NET = "ASP.NET"

    # Databases
    MySQL = "MySQL"
    PostgreSQL = "PostgreSQL"
    MongoDB = "MongoDB"
    Redis = "Redis"
    SQLite = "SQLite"
    Oracle_DB = "Oracle DB"
    Firebase = "Firebase"
    Cassandra = "Cassandra"

    # DevOps / Cloud
    Docker = "Docker"
    Kubernetes = "Kubernetes"
    AWS = "AWS"
    Azure = "Azure"
    Google_Cloud = "Google Cloud"
    CICD = "CI/CD"
    Terraform = "Terraform"
    Nginx = "Nginx"

    # AI / ML
    TensorFlow = "TensorFlow"
    PyTorch = "PyTorch"
    Scikit_learn = "Scikit-learn"
    OpenCV = "OpenCV"
    Pandas = "Pandas"
    NumPy = "NumPy"
    LangChain = "LangChain"
    HuggingFace = "HuggingFace"
    LLMs = "LLMs"
    RAG = "RAG"

    # Tools
    Git = "Git"
    GitHub = "GitHub"
    GitLab = "GitLab"
    Linux = "Linux"
    Postman = "Postman"
    Jira = "Jira"

    # Other
    REST_API = "REST API"
    GraphQL = "GraphQL"
    Microservices = "Microservices"
    System_Design = "System Design"
    Data_Structures = "Data Structures"
    Algorithms = "Algorithms"