from enum import Enum


class TopicEnum(str, Enum):

    C_Programming = "C Programming"
    Cpp_Programming = "C++ Programming"
    Java_Programming = "Java Programming"
    Python_Programming = "Python Programming"
    JavaScript_Programming = "JavaScript Programming"
    TypeScript_Programming = "TypeScript Programming"
    Go_Programming = "Go Programming"
    Rust_Programming = "Rust Programming"
    Kotlin_Programming = "Kotlin Programming"
    Swift_Programming = "Swift Programming"
    PHP_Programming = "PHP Programming"
    CSharp_Programming = "C# Programming"
    R_Programming = "R Programming"
    Dart_Programming = "Dart Programming"
    Scala_Programming = "Scala Programming"
    Bash_Scripting = "Bash Scripting"
    Assembly_Programming = "Assembly Programming"
    MATLAB_Programming = "MATLAB Programming"
    Groovy_Programming = "Groovy Programming"
    Haskell_Programming = "Haskell Programming"
    Elixir_Programming = "Elixir Programming"
    Julia_Programming = "Julia Programming"
    COBOL_Programming = "COBOL Programming"
    Fortran_Programming = "Fortran Programming"
    Solidity_Programming = "Solidity Programming"
    VBA_Programming = "VBA Programming"
    Objective_C_Programming = "Objective-C Programming"
    PowerShell_Scripting = "PowerShell Scripting"
    Scratch_Programming = "Scratch Programming"
    Crystal_Programming = "Crystal Programming"
    Nim_Programming = "Nim Programming"
    Ada_Programming = "Ada Programming"
    GDScript_Programming = "GDScript Programming"
    FSharp_Programming = "F# Programming"
    Perl_Programming = "Perl Programming"
    Shell_Scripting = "Shell Scripting"
    WebAssembly_Programming = "WebAssembly Programming"
    PLSQL_Programming = "PL/SQL Programming"
    ABAP_Programming = "ABAP Programming"
    Hack_HHVM_Programming = "Hack (HHVM) Programming"
    Zig_Programming = "Zig Programming"
    Verilog_Programming = "Verilog Programming"
    VHDL_Programming = "VHDL Programming"

    HTML_Development = "HTML Development"
    CSS_Development = "CSS Development"
    React_Development = "React Development"
    NextJS_Development = "Next.js Development"
    Angular_Development = "Angular Development"
    VueJS_Development = "Vue.js Development"
    Tailwind_CSS_Development = "Tailwind CSS Development"
    Bootstrap_Framework = "Bootstrap Framework"

    NodeJS_Development = "Node.js Development"
    ExpressJS_Development = "Express.js Development"
    Django_Development = "Django Development"
    Flask_Development = "Flask Development"
    FastAPI_Development = "FastAPI Development"
    Spring_Boot_Development = "Spring Boot Development"
    ASP_NET_Development = "ASP.NET Development"

    MySQL_Database = "MySQL Database"
    PostgreSQL_Database = "PostgreSQL Database"
    MongoDB_Database = "MongoDB Database"
    Redis_Database = "Redis Database"
    SQLite_Database = "SQLite Database"
    Oracle_Database = "Oracle Database"
    Firebase_Development = "Firebase Development"
    Cassandra_Database = "Cassandra Database"

    Docker_Containerization = "Docker Containerization"
    Kubernetes_Orchestration = "Kubernetes Orchestration"
    Amazon_Web_Services = "Amazon Web Services"
    Microsoft_Azure = "Microsoft Azure"
    Google_Cloud_Platform = "Google Cloud Platform"
    CICD_Pipeline = "CI/CD Pipeline"
    Terraform_Infrastructure = "Terraform Infrastructure"
    Nginx_Server = "Nginx Server"

    TensorFlow_Framework = "TensorFlow Framework"
    PyTorch_Framework = "PyTorch Framework"
    Scikit_learn_Library = "Scikit-learn Library"
    OpenCV_Library = "OpenCV Library"
    Pandas_Library = "Pandas Library"
    NumPy_Library = "NumPy Library"
    LangChain_Framework = "LangChain Framework"
    HuggingFace_Transformers = "HuggingFace Transformers"
    Large_Language_Models = "Large Language Models"
    Retrieval_Augmented_Generation = "Retrieval Augmented Generation"

    Git_Version_Control = "Git Version Control"
    GitHub_Platform = "GitHub Platform"
    GitLab_Platform = "GitLab Platform"
    Linux_Operating_System = "Linux Operating System"
    Postman_API_Testing = "Postman API Testing"
    Jira_Project_Management = "Jira Project Management"

    REST_API_Development = "REST API Development"
    GraphQL_API_Development = "GraphQL API Development"
    Microservices_Architecture = "Microservices Architecture"
    System_Design = "System Design"
    Data_Structures = "Data Structures"
    Algorithms = "Algorithms"
    Object_Oriented_Programming = "Object Oriented Programming"

    Operating_Systems = "Operating Systems"
    Database_Management_Systems = "Database Management Systems"
    Computer_Networks = "Computer Networks"
    Software_Engineering = "Software Engineering"
    Compiler_Design = "Compiler Design"
    Theory_of_Computation = "Theory of Computation"
    Digital_Logic_Design = "Digital Logic Design"
    Computer_Organization_and_Architecture = "Computer Organization and Architecture"
    Microprocessors = "Microprocessors"

    Artificial_Intelligence = "Artificial Intelligence"
    Machine_Learning = "Machine Learning"
    Deep_Learning = "Deep Learning"
    Natural_Language_Processing = "Natural Language Processing"
    Computer_Vision = "Computer Vision"
    Distributed_Systems = "Distributed Systems"
    Cloud_Computing = "Cloud Computing"
    Parallel_Computing = "Parallel Computing"
    Big_Data = "Big Data"

    Discrete_Mathematics = "Discrete Mathematics"
    Linear_Algebra = "Linear Algebra"
    Probability_and_Statistics = "Probability and Statistics"
    Numerical_Methods = "Numerical Methods"

    Cryptography = "Cryptography"
    Cyber_Security = "Cyber Security"
    Information_Security = "Information Security"

    Design_Patterns = "Design Patterns"
    Software_Testing = "Software Testing"
    Agile_Methodology = "Agile Methodology"
    DevOps = "DevOps"

    Human_Computer_Interaction = "Human Computer Interaction"
    Blockchain_Technology = "Blockchain Technology"
    Internet_of_Things = "Internet of Things"
    Mobile_Computing = "Mobile Computing"

        # High-Level Development Domains
    Frontend_Development = "Frontend Development"
    Backend_Development = "Backend Development"
    Full_Stack_Development = "Full Stack Development"
    Web_Development = "Web Development"
    Mobile_App_Development = "Mobile App Development"

    # Cloud & Deployment
    Cloud_Deployment = "Cloud Deployment"
    Cloud_Infrastructure = "Cloud Infrastructure"
    DevOps_Practices = "DevOps Practices"
    Site_Reliability_Engineering = "Site Reliability Engineering"
    Platform_Engineering = "Platform Engineering"

    # AI / Data Domains
    Generative_AI = "Generative AI"
    Data_Engineering = "Data Engineering"
    Big_Data_Engineering = "Big Data Engineering"

    # Systems Domains
    Embedded_Systems = "Embedded Systems"
    Game_Development = "Game Development"
    Graphics_Programming = "Graphics Programming"

    # Security Domains
    Cybersecurity = "Cybersecurity"
    Penetration_Testing = "Penetration Testing"
    Security_Engineering = "Security Engineering"

    # Architecture & Leadership
    Software_Architecture = "Software Architecture"
    Technical_Leadership = "Technical Leadership"
    Engineering_Management = "Engineering Management"

    # Emerging Domains
    AR_VR_Development = "AR/VR Development"
    Blockchain_Development = "Blockchain Development"